### ISSUE TITLE
We are still getting Non PSD errors in solve_posdef

### ISSUE THREAD

**Issue by dsteinberg** [NICTA/revrand#100]
From #98 
```
Traceback (most recent call last):
File "...\site-packages\revrand-0.4.1-py3.5.egg\revrand\mathfun\linalg.py", line 114, in solve_posdef
L = cholesky(A, lower=lower)
File "...\site-packages\scipy\linalg\decomp_cholesky.py", line 81, in cholesky check_finite=check_finite)
File "...\site-packages\scipy\linalg\decomp_cholesky.py", line 30, in _cholesky raise LinAlgError("%d-th leading minor not positive definite" % info)
```

**Comment by dsteinberg** [comment]
Found some big problems in `solve_posdef`, maybe even logdet had wrong sign too.
