### ISSUE TITLE
Cannot install :(

### ISSUE THREAD

**Issue by ltiao** [NICTA/revrand#90]
``` console
$ python setup.py install
running install
running bdist_egg
running egg_info
writing revrand.egg-info/PKG-INFO
writing top-level names to revrand.egg-info/top_level.txt
writing dependency_links to revrand.egg-info/dependency_links.txt
writing requirements to revrand.egg-info/requires.txt
reading manifest file 'revrand.egg-info/SOURCES.txt'
writing manifest file 'revrand.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
copying revrand.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying revrand.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying revrand.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying revrand.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying revrand.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    "Topic :: Scientific/Engineering :: Information Analysis"
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Users/tia00c/.virtualenvs/revrand/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by ltiao** [comment]
N.B. Could have something to do with CSIRO IT Migrations...

**Comment by dsteinberg** [comment]
could it be bad `*.pyc` files or `__pycache__` folders?

**Comment by ltiao** [comment]
Tried deleting those

**Comment by dsteinberg** [comment]
Remake your virtualenv?

**Comment by ltiao** [comment]
Had to delete all my virtualenvs after the migration...

**Comment by dsteinberg** [comment]
:-s

**Comment by dsteinberg** [comment]
reopen this if this is not an issue with your computer @ltiao
